image: registry.gitlab.com/maxmanders/maxmanders.co.uk:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - jekyll build
  artifacts:
    paths:
      - _site
  when: always
  only:
    - master

deploy:
  stage: deploy
  script:
    - aws s3 sync --delete _site/ s3://${S3_BUCKET}/
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
  artifacts:
    paths:
      - _site
  when: always
  only:
    - master
