image: minn/jekyll-gen

cache:
  paths: 
    - vendor/

before_script:
  - apt-get update
  - apt-get install libmagickwand-dev imagemagick
  - bundle install
  
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public

vars:
  stage: test
  script:
    - 'export S3_ID="$(echo "$ACCESS_KEY_ID")" >> s3_deploy_vars'
    - 'export S3_SECRET="$(echo "$SECRET_ACCESS_KEY")" > s3_deploy_vars'
    - 'export S3_BUCKET="$(echo "$S3_BUCKET")" > s3_deploy_vars'
  artifacts:
    paths:
      - s3_deploy_vars

deploy:
  stage: deploy
  script:
    - source s3_deploy_vars
    - bundle exec s3_website push
  artifacts:
    paths:
      - public
  only:
    - master