---
markdown: kramdown
highlighter: rouge

exclude: [rakefile, vendor, Gemfile, Gemfile.lock, rakefile, s3_website.yml]

title: Max Manders
tagline: 'Thoughts on DevOps'
description: 'My thoughts on software deveopment, operations and infrastructure.'
url: http://maxmanders.co.uk
baseurl: /
timezone: nil
excerpt_separator: <!--more-->
paginate: 5
paginate_path: 'page:num'
permalink: /:year/:month/:day/:title

author:
  name: 'Max Manders'
  url: https://twitter.com/maxmanders

social:
  - title: github
    url: https://github.com/maxmanders/
  - title: twitter
    url: https://twitter.com/maxmanders/
  - title: pinboard
    url: https://www.pinboard.in/u:maxmanders/
  - title: lastfm
    url: https://www.last.fm/user/mmanders/
  - title: linkedin
    url: https://uk.linkedin.com/in/maxmanders
  - title: rss
    url: https://maxmanders.co.uk/feed/rss.xml

plugins: 
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-tidy
