baseURL: "https://maxmanders.co.uk/"
title: "Max Manders"
theme: "hyde"
languageCode: "en-gb"
disqusShortname: "maxmanders"

params:
  description: "a bit of dev / a bit of ops"

frontmatter:
  date:
  - :filename
  - :default

permalinks:
  posts: /:year/:month/:day/:title/

Menus:
  main:
    - Name: "Github"
      URL: "https://github.com/maxmanders/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/maxmanders/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/maxmanders"

deployment:
  targets:
    URL: "s3://www.maxmanders.co.uk?region=eu-west-1"
    cloudFrontDistributionID: "E2GJBABJUJJTHC"
  matchers:
    - pattern: "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
      cacheControl: "max-age=31536000, no-transform, public"
      gzip: true
    - pattern: "^.+\\.(html|xml|json)$"
      gzip: true
